# Generated by Django 4.0 on 2026-04-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPG',
            fields=[
                ('ab_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ab_name', models.CharField(max_length=100)),
                ('ab_price', models.CharField(max_length=100)),
                ('ab_details', models.CharField(max_length=100)),
                ('ab_address', models.CharField(default='', max_length=100)),
                ('ab_location', models.TextField(default='', max_length=100)),
                ('ab_image', models.ImageField(upload_to='app/static/media/pg/')),
                ('ab_status', models.IntegerField(default=0)),
                ('ab_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddVendors',
            fields=[
                ('av_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('av_name', models.CharField(max_length=100)),
                ('av_mobile', models.CharField(max_length=100)),
                ('av_email', models.CharField(max_length=100)),
                ('av_password', models.CharField(max_length=100)),
                ('av_role', models.CharField(max_length=100)),
                ('av_status', models.IntegerField(default=0)),
                ('av_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_mobile', models.CharField(max_length=100)),
                ('ad_email', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
                ('ad_role', models.CharField(max_length=100)),
                ('ad_status', models.IntegerField(default=0)),
                ('ad_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_name', models.CharField(max_length=100)),
                ('ct_mobile', models.CharField(max_length=100)),
                ('ct_email', models.CharField(max_length=100)),
                ('ct_subject', models.CharField(max_length=100)),
                ('ct_message', models.CharField(default='', max_length=100)),
                ('ct_status', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('fp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fp_email', models.CharField(default='', max_length=100)),
                ('fp_otp', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('or_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('or_name', models.CharField(max_length=100)),
                ('or_total_amount', models.CharField(max_length=100)),
                ('or_address', models.CharField(max_length=100)),
                ('or_ordered_by', models.CharField(max_length=100)),
                ('or_transaction_id', models.CharField(max_length=100)),
                ('or_status', models.CharField(default=0, max_length=100)),
                ('or_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rg_name', models.CharField(max_length=100)),
                ('rg_mobile', models.CharField(max_length=100)),
                ('rg_email', models.CharField(max_length=100)),
                ('rg_password', models.CharField(max_length=100)),
                ('rg_address', models.CharField(default='', max_length=100)),
                ('rg_status', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rv_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rv_pg_id', models.CharField(default='', max_length=100)),
                ('rv_name', models.CharField(max_length=100)),
                ('rv_mobile', models.CharField(max_length=100)),
                ('rv_email', models.CharField(max_length=100)),
                ('rv_review', models.CharField(default='', max_length=100)),
                ('rv_status', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
